# Generated by Django for removing payment gateway integration
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='lemon_squeezy_subscription_id',
        ),
    ]