# Generated by Django 5.1.5 on 2025-08-06 10:33

from django.db import migrations


def fix_username_fields(apps, schema_editor):
    """
    Ensure all existing users have username set to their email
    """
    User = apps.get_model('accounts', 'User')
    
    for user in User.objects.all():
        if not user.username or user.username != user.email:
            user.username = user.email
            user.save(update_fields=['username'])


def reverse_username_fields(apps, schema_editor):
    """
    Reverse migration - no action needed
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_managers_alter_user_email_and_more'),
    ]

    operations = [
        migrations.RunPython(fix_username_fields, reverse_username_fields),
    ]
